//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.GetMark_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Member", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Member : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _ClassField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Class {
            get {
                return this._ClassField;
            }
            set {
                if ((object.ReferenceEquals(this._ClassField, value) != true)) {
                    this._ClassField = value;
                    this.RaisePropertyChanged("_Class");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SinhVien", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class SinhVien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DantocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiachiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DienthoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GioitinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotenchaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotenmeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KhoahocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MssvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NganhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NgaysinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NghenghiepchaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NghenghiepmeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoisinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuoctichField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TongTCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TongiaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dantoc {
            get {
                return this.DantocField;
            }
            set {
                if ((object.ReferenceEquals(this.DantocField, value) != true)) {
                    this.DantocField = value;
                    this.RaisePropertyChanged("Dantoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Diachi {
            get {
                return this.DiachiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiachiField, value) != true)) {
                    this.DiachiField = value;
                    this.RaisePropertyChanged("Diachi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dienthoai {
            get {
                return this.DienthoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.DienthoaiField, value) != true)) {
                    this.DienthoaiField = value;
                    this.RaisePropertyChanged("Dienthoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gioitinh {
            get {
                return this.GioitinhField;
            }
            set {
                if ((this.GioitinhField.Equals(value) != true)) {
                    this.GioitinhField = value;
                    this.RaisePropertyChanged("Gioitinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeDT {
            get {
                return this.HeDTField;
            }
            set {
                if ((object.ReferenceEquals(this.HeDTField, value) != true)) {
                    this.HeDTField = value;
                    this.RaisePropertyChanged("HeDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hoten {
            get {
                return this.HotenField;
            }
            set {
                if ((object.ReferenceEquals(this.HotenField, value) != true)) {
                    this.HotenField = value;
                    this.RaisePropertyChanged("Hoten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hotencha {
            get {
                return this.HotenchaField;
            }
            set {
                if ((object.ReferenceEquals(this.HotenchaField, value) != true)) {
                    this.HotenchaField = value;
                    this.RaisePropertyChanged("Hotencha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hotenme {
            get {
                return this.HotenmeField;
            }
            set {
                if ((object.ReferenceEquals(this.HotenmeField, value) != true)) {
                    this.HotenmeField = value;
                    this.RaisePropertyChanged("Hotenme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Khoa {
            get {
                return this.KhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.KhoaField, value) != true)) {
                    this.KhoaField = value;
                    this.RaisePropertyChanged("Khoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Khoahoc {
            get {
                return this.KhoahocField;
            }
            set {
                if ((object.ReferenceEquals(this.KhoahocField, value) != true)) {
                    this.KhoahocField = value;
                    this.RaisePropertyChanged("Khoahoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lop {
            get {
                return this.LopField;
            }
            set {
                if ((object.ReferenceEquals(this.LopField, value) != true)) {
                    this.LopField = value;
                    this.RaisePropertyChanged("Lop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mssv {
            get {
                return this.MssvField;
            }
            set {
                if ((object.ReferenceEquals(this.MssvField, value) != true)) {
                    this.MssvField = value;
                    this.RaisePropertyChanged("Mssv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nganh {
            get {
                return this.NganhField;
            }
            set {
                if ((object.ReferenceEquals(this.NganhField, value) != true)) {
                    this.NganhField = value;
                    this.RaisePropertyChanged("Nganh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ngaysinh {
            get {
                return this.NgaysinhField;
            }
            set {
                if ((object.ReferenceEquals(this.NgaysinhField, value) != true)) {
                    this.NgaysinhField = value;
                    this.RaisePropertyChanged("Ngaysinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nghenghiepcha {
            get {
                return this.NghenghiepchaField;
            }
            set {
                if ((object.ReferenceEquals(this.NghenghiepchaField, value) != true)) {
                    this.NghenghiepchaField = value;
                    this.RaisePropertyChanged("Nghenghiepcha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nghenghiepme {
            get {
                return this.NghenghiepmeField;
            }
            set {
                if ((object.ReferenceEquals(this.NghenghiepmeField, value) != true)) {
                    this.NghenghiepmeField = value;
                    this.RaisePropertyChanged("Nghenghiepme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Noisinh {
            get {
                return this.NoisinhField;
            }
            set {
                if ((object.ReferenceEquals(this.NoisinhField, value) != true)) {
                    this.NoisinhField = value;
                    this.RaisePropertyChanged("Noisinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quoctich {
            get {
                return this.QuoctichField;
            }
            set {
                if ((object.ReferenceEquals(this.QuoctichField, value) != true)) {
                    this.QuoctichField = value;
                    this.RaisePropertyChanged("Quoctich");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TongTC {
            get {
                return this.TongTCField;
            }
            set {
                if ((this.TongTCField.Equals(value) != true)) {
                    this.TongTCField = value;
                    this.RaisePropertyChanged("TongTC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tongiao {
            get {
                return this.TongiaoField;
            }
            set {
                if ((object.ReferenceEquals(this.TongiaoField, value) != true)) {
                    this.TongiaoField = value;
                    this.RaisePropertyChanged("Tongiao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KetQua", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class KetQua : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float DTB_h10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float DTB_h4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DTB_hchuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float DiemKTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float DiemThiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaMHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoTCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoTietField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenMHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TinhtrangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float DTB_h10 {
            get {
                return this.DTB_h10Field;
            }
            set {
                if ((this.DTB_h10Field.Equals(value) != true)) {
                    this.DTB_h10Field = value;
                    this.RaisePropertyChanged("DTB_h10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float DTB_h4 {
            get {
                return this.DTB_h4Field;
            }
            set {
                if ((this.DTB_h4Field.Equals(value) != true)) {
                    this.DTB_h4Field = value;
                    this.RaisePropertyChanged("DTB_h4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DTB_hchu {
            get {
                return this.DTB_hchuField;
            }
            set {
                if ((object.ReferenceEquals(this.DTB_hchuField, value) != true)) {
                    this.DTB_hchuField = value;
                    this.RaisePropertyChanged("DTB_hchu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float DiemKT {
            get {
                return this.DiemKTField;
            }
            set {
                if ((this.DiemKTField.Equals(value) != true)) {
                    this.DiemKTField = value;
                    this.RaisePropertyChanged("DiemKT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float DiemThi {
            get {
                return this.DiemThiField;
            }
            set {
                if ((this.DiemThiField.Equals(value) != true)) {
                    this.DiemThiField = value;
                    this.RaisePropertyChanged("DiemThi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Loai {
            get {
                return this.LoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.LoaiField, value) != true)) {
                    this.LoaiField = value;
                    this.RaisePropertyChanged("Loai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaMH {
            get {
                return this.MaMHField;
            }
            set {
                if ((object.ReferenceEquals(this.MaMHField, value) != true)) {
                    this.MaMHField = value;
                    this.RaisePropertyChanged("MaMH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoTC {
            get {
                return this.SoTCField;
            }
            set {
                if ((this.SoTCField.Equals(value) != true)) {
                    this.SoTCField = value;
                    this.RaisePropertyChanged("SoTC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoTiet {
            get {
                return this.SoTietField;
            }
            set {
                if ((this.SoTietField.Equals(value) != true)) {
                    this.SoTietField = value;
                    this.RaisePropertyChanged("SoTiet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenMH {
            get {
                return this.TenMHField;
            }
            set {
                if ((object.ReferenceEquals(this.TenMHField, value) != true)) {
                    this.TenMHField = value;
                    this.RaisePropertyChanged("TenMH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Tinhtrang {
            get {
                return this.TinhtrangField;
            }
            set {
                if ((this.TinhtrangField.Equals(value) != true)) {
                    this.TinhtrangField = value;
                    this.RaisePropertyChanged("Tinhtrang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SV_HK", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class SV_HK : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HockyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MssvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TBHKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TC_dat_HKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TC_dk_HKField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hocky {
            get {
                return this.HockyField;
            }
            set {
                if ((object.ReferenceEquals(this.HockyField, value) != true)) {
                    this.HockyField = value;
                    this.RaisePropertyChanged("Hocky");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mssv {
            get {
                return this.MssvField;
            }
            set {
                if ((object.ReferenceEquals(this.MssvField, value) != true)) {
                    this.MssvField = value;
                    this.RaisePropertyChanged("Mssv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TBHK {
            get {
                return this.TBHKField;
            }
            set {
                if ((this.TBHKField.Equals(value) != true)) {
                    this.TBHKField = value;
                    this.RaisePropertyChanged("TBHK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TC_dat_HK {
            get {
                return this.TC_dat_HKField;
            }
            set {
                if ((this.TC_dat_HKField.Equals(value) != true)) {
                    this.TC_dat_HKField = value;
                    this.RaisePropertyChanged("TC_dat_HK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TC_dk_HK {
            get {
                return this.TC_dk_HKField;
            }
            set {
                if ((this.TC_dk_HKField.Equals(value) != true)) {
                    this.TC_dk_HKField = value;
                    this.RaisePropertyChanged("TC_dk_HK");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Statistic", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Statistic : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TB_tichluyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TongMHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TongMH_noField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TongTC_datField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TongTC_dkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Tong_gioiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Tong_kemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Tong_khaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Tong_trungbinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Tong_xuatsacField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TB_tichluy {
            get {
                return this.TB_tichluyField;
            }
            set {
                if ((this.TB_tichluyField.Equals(value) != true)) {
                    this.TB_tichluyField = value;
                    this.RaisePropertyChanged("TB_tichluy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TongMH {
            get {
                return this.TongMHField;
            }
            set {
                if ((this.TongMHField.Equals(value) != true)) {
                    this.TongMHField = value;
                    this.RaisePropertyChanged("TongMH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TongMH_no {
            get {
                return this.TongMH_noField;
            }
            set {
                if ((this.TongMH_noField.Equals(value) != true)) {
                    this.TongMH_noField = value;
                    this.RaisePropertyChanged("TongMH_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TongTC_dat {
            get {
                return this.TongTC_datField;
            }
            set {
                if ((this.TongTC_datField.Equals(value) != true)) {
                    this.TongTC_datField = value;
                    this.RaisePropertyChanged("TongTC_dat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TongTC_dk {
            get {
                return this.TongTC_dkField;
            }
            set {
                if ((this.TongTC_dkField.Equals(value) != true)) {
                    this.TongTC_dkField = value;
                    this.RaisePropertyChanged("TongTC_dk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tong_gioi {
            get {
                return this.Tong_gioiField;
            }
            set {
                if ((this.Tong_gioiField.Equals(value) != true)) {
                    this.Tong_gioiField = value;
                    this.RaisePropertyChanged("Tong_gioi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tong_kem {
            get {
                return this.Tong_kemField;
            }
            set {
                if ((this.Tong_kemField.Equals(value) != true)) {
                    this.Tong_kemField = value;
                    this.RaisePropertyChanged("Tong_kem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tong_kha {
            get {
                return this.Tong_khaField;
            }
            set {
                if ((this.Tong_khaField.Equals(value) != true)) {
                    this.Tong_khaField = value;
                    this.RaisePropertyChanged("Tong_kha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tong_trungbinh {
            get {
                return this.Tong_trungbinhField;
            }
            set {
                if ((this.Tong_trungbinhField.Equals(value) != true)) {
                    this.Tong_trungbinhField = value;
                    this.RaisePropertyChanged("Tong_trungbinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tong_xuatsac {
            get {
                return this.Tong_xuatsacField;
            }
            set {
                if ((this.Tong_xuatsacField.Equals(value) != true)) {
                    this.Tong_xuatsacField = value;
                    this.RaisePropertyChanged("Tong_xuatsac");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetMark_Service.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/GetAuthors", ReplyAction="http://tempuri.org/IService/GetAuthorsResponse")]
        Client.GetMark_Service.Member[] GetAuthors();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/GetAuthors", ReplyAction="http://tempuri.org/IService/GetAuthorsResponse")]
        System.IAsyncResult BeginGetAuthors(System.AsyncCallback callback, object asyncState);
        
        Client.GetMark_Service.Member[] EndGetAuthors(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/Download", ReplyAction="http://tempuri.org/IService/DownloadResponse")]
        int Download(string path);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/Download", ReplyAction="http://tempuri.org/IService/DownloadResponse")]
        System.IAsyncResult BeginDownload(string path, System.AsyncCallback callback, object asyncState);
        
        int EndDownload(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/GetResource", ReplyAction="http://tempuri.org/IService/GetResourceResponse")]
        byte[] GetResource(string resName);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/GetResource", ReplyAction="http://tempuri.org/IService/GetResourceResponse")]
        System.IAsyncResult BeginGetResource(string resName, System.AsyncCallback callback, object asyncState);
        
        byte[] EndGetResource(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/CheckLogin", ReplyAction="http://tempuri.org/IService/CheckLoginResponse")]
        bool CheckLogin(string username, string password, int mode);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/CheckLogin", ReplyAction="http://tempuri.org/IService/CheckLoginResponse")]
        System.IAsyncResult BeginCheckLogin(string username, string password, int mode, System.AsyncCallback callback, object asyncState);
        
        bool EndCheckLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/GetInfoSV", ReplyAction="http://tempuri.org/IService/GetInfoSVResponse")]
        Client.GetMark_Service.SinhVien GetInfoSV(string MSSV);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/GetInfoSV", ReplyAction="http://tempuri.org/IService/GetInfoSVResponse")]
        System.IAsyncResult BeginGetInfoSV(string MSSV, System.AsyncCallback callback, object asyncState);
        
        Client.GetMark_Service.SinhVien EndGetInfoSV(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/UpdateInfoSV", ReplyAction="http://tempuri.org/IService/UpdateInfoSVResponse")]
        bool UpdateInfoSV(Client.GetMark_Service.SinhVien SV);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/UpdateInfoSV", ReplyAction="http://tempuri.org/IService/UpdateInfoSVResponse")]
        System.IAsyncResult BeginUpdateInfoSV(Client.GetMark_Service.SinhVien SV, System.AsyncCallback callback, object asyncState);
        
        bool EndUpdateInfoSV(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/List_HK", ReplyAction="http://tempuri.org/IService/List_HKResponse")]
        string[] List_HK();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/List_HK", ReplyAction="http://tempuri.org/IService/List_HKResponse")]
        System.IAsyncResult BeginList_HK(System.AsyncCallback callback, object asyncState);
        
        string[] EndList_HK(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/KetQua_HK", ReplyAction="http://tempuri.org/IService/KetQua_HKResponse")]
        Client.GetMark_Service.KetQua[] KetQua_HK(string MSSV, string HK);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/KetQua_HK", ReplyAction="http://tempuri.org/IService/KetQua_HKResponse")]
        System.IAsyncResult BeginKetQua_HK(string MSSV, string HK, System.AsyncCallback callback, object asyncState);
        
        Client.GetMark_Service.KetQua[] EndKetQua_HK(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/InfoSV_HK", ReplyAction="http://tempuri.org/IService/InfoSV_HKResponse")]
        Client.GetMark_Service.SV_HK InfoSV_HK(string MSSV, string HK);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/InfoSV_HK", ReplyAction="http://tempuri.org/IService/InfoSV_HKResponse")]
        System.IAsyncResult BeginInfoSV_HK(string MSSV, string HK, System.AsyncCallback callback, object asyncState);
        
        Client.GetMark_Service.SV_HK EndInfoSV_HK(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/Info_Statistic", ReplyAction="http://tempuri.org/IService/Info_StatisticResponse")]
        Client.GetMark_Service.Statistic Info_Statistic(string MSSV);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/Info_Statistic", ReplyAction="http://tempuri.org/IService/Info_StatisticResponse")]
        System.IAsyncResult BeginInfo_Statistic(string MSSV, System.AsyncCallback callback, object asyncState);
        
        Client.GetMark_Service.Statistic EndInfo_Statistic(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Client.GetMark_Service.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAuthorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAuthorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client.GetMark_Service.Member[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client.GetMark_Service.Member[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DownloadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DownloadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetResourceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetResourceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public byte[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CheckLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetInfoSVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetInfoSVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client.GetMark_Service.SinhVien Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client.GetMark_Service.SinhVien)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateInfoSVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateInfoSVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class List_HKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public List_HKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KetQua_HKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public KetQua_HKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client.GetMark_Service.KetQua[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client.GetMark_Service.KetQua[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InfoSV_HKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InfoSV_HKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client.GetMark_Service.SV_HK Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client.GetMark_Service.SV_HK)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Info_StatisticCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Info_StatisticCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client.GetMark_Service.Statistic Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client.GetMark_Service.Statistic)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Client.GetMark_Service.IService>, Client.GetMark_Service.IService {
        
        private BeginOperationDelegate onBeginGetAuthorsDelegate;
        
        private EndOperationDelegate onEndGetAuthorsDelegate;
        
        private System.Threading.SendOrPostCallback onGetAuthorsCompletedDelegate;
        
        private BeginOperationDelegate onBeginDownloadDelegate;
        
        private EndOperationDelegate onEndDownloadDelegate;
        
        private System.Threading.SendOrPostCallback onDownloadCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetResourceDelegate;
        
        private EndOperationDelegate onEndGetResourceDelegate;
        
        private System.Threading.SendOrPostCallback onGetResourceCompletedDelegate;
        
        private BeginOperationDelegate onBeginCheckLoginDelegate;
        
        private EndOperationDelegate onEndCheckLoginDelegate;
        
        private System.Threading.SendOrPostCallback onCheckLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetInfoSVDelegate;
        
        private EndOperationDelegate onEndGetInfoSVDelegate;
        
        private System.Threading.SendOrPostCallback onGetInfoSVCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateInfoSVDelegate;
        
        private EndOperationDelegate onEndUpdateInfoSVDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateInfoSVCompletedDelegate;
        
        private BeginOperationDelegate onBeginList_HKDelegate;
        
        private EndOperationDelegate onEndList_HKDelegate;
        
        private System.Threading.SendOrPostCallback onList_HKCompletedDelegate;
        
        private BeginOperationDelegate onBeginKetQua_HKDelegate;
        
        private EndOperationDelegate onEndKetQua_HKDelegate;
        
        private System.Threading.SendOrPostCallback onKetQua_HKCompletedDelegate;
        
        private BeginOperationDelegate onBeginInfoSV_HKDelegate;
        
        private EndOperationDelegate onEndInfoSV_HKDelegate;
        
        private System.Threading.SendOrPostCallback onInfoSV_HKCompletedDelegate;
        
        private BeginOperationDelegate onBeginInfo_StatisticDelegate;
        
        private EndOperationDelegate onEndInfo_StatisticDelegate;
        
        private System.Threading.SendOrPostCallback onInfo_StatisticCompletedDelegate;
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetAuthorsCompletedEventArgs> GetAuthorsCompleted;
        
        public event System.EventHandler<DownloadCompletedEventArgs> DownloadCompleted;
        
        public event System.EventHandler<GetResourceCompletedEventArgs> GetResourceCompleted;
        
        public event System.EventHandler<CheckLoginCompletedEventArgs> CheckLoginCompleted;
        
        public event System.EventHandler<GetInfoSVCompletedEventArgs> GetInfoSVCompleted;
        
        public event System.EventHandler<UpdateInfoSVCompletedEventArgs> UpdateInfoSVCompleted;
        
        public event System.EventHandler<List_HKCompletedEventArgs> List_HKCompleted;
        
        public event System.EventHandler<KetQua_HKCompletedEventArgs> KetQua_HKCompleted;
        
        public event System.EventHandler<InfoSV_HKCompletedEventArgs> InfoSV_HKCompleted;
        
        public event System.EventHandler<Info_StatisticCompletedEventArgs> Info_StatisticCompleted;
        
        public Client.GetMark_Service.Member[] GetAuthors() {
            return base.Channel.GetAuthors();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAuthors(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAuthors(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Client.GetMark_Service.Member[] EndGetAuthors(System.IAsyncResult result) {
            return base.Channel.EndGetAuthors(result);
        }
        
        private System.IAsyncResult OnBeginGetAuthors(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetAuthors(callback, asyncState);
        }
        
        private object[] OnEndGetAuthors(System.IAsyncResult result) {
            Client.GetMark_Service.Member[] retVal = this.EndGetAuthors(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAuthorsCompleted(object state) {
            if ((this.GetAuthorsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAuthorsCompleted(this, new GetAuthorsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAuthorsAsync() {
            this.GetAuthorsAsync(null);
        }
        
        public void GetAuthorsAsync(object userState) {
            if ((this.onBeginGetAuthorsDelegate == null)) {
                this.onBeginGetAuthorsDelegate = new BeginOperationDelegate(this.OnBeginGetAuthors);
            }
            if ((this.onEndGetAuthorsDelegate == null)) {
                this.onEndGetAuthorsDelegate = new EndOperationDelegate(this.OnEndGetAuthors);
            }
            if ((this.onGetAuthorsCompletedDelegate == null)) {
                this.onGetAuthorsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAuthorsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAuthorsDelegate, null, this.onEndGetAuthorsDelegate, this.onGetAuthorsCompletedDelegate, userState);
        }
        
        public int Download(string path) {
            return base.Channel.Download(path);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDownload(string path, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDownload(path, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndDownload(System.IAsyncResult result) {
            return base.Channel.EndDownload(result);
        }
        
        private System.IAsyncResult OnBeginDownload(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string path = ((string)(inValues[0]));
            return this.BeginDownload(path, callback, asyncState);
        }
        
        private object[] OnEndDownload(System.IAsyncResult result) {
            int retVal = this.EndDownload(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDownloadCompleted(object state) {
            if ((this.DownloadCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DownloadCompleted(this, new DownloadCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DownloadAsync(string path) {
            this.DownloadAsync(path, null);
        }
        
        public void DownloadAsync(string path, object userState) {
            if ((this.onBeginDownloadDelegate == null)) {
                this.onBeginDownloadDelegate = new BeginOperationDelegate(this.OnBeginDownload);
            }
            if ((this.onEndDownloadDelegate == null)) {
                this.onEndDownloadDelegate = new EndOperationDelegate(this.OnEndDownload);
            }
            if ((this.onDownloadCompletedDelegate == null)) {
                this.onDownloadCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDownloadCompleted);
            }
            base.InvokeAsync(this.onBeginDownloadDelegate, new object[] {
                        path}, this.onEndDownloadDelegate, this.onDownloadCompletedDelegate, userState);
        }
        
        public byte[] GetResource(string resName) {
            return base.Channel.GetResource(resName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetResource(string resName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetResource(resName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public byte[] EndGetResource(System.IAsyncResult result) {
            return base.Channel.EndGetResource(result);
        }
        
        private System.IAsyncResult OnBeginGetResource(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string resName = ((string)(inValues[0]));
            return this.BeginGetResource(resName, callback, asyncState);
        }
        
        private object[] OnEndGetResource(System.IAsyncResult result) {
            byte[] retVal = this.EndGetResource(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetResourceCompleted(object state) {
            if ((this.GetResourceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetResourceCompleted(this, new GetResourceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetResourceAsync(string resName) {
            this.GetResourceAsync(resName, null);
        }
        
        public void GetResourceAsync(string resName, object userState) {
            if ((this.onBeginGetResourceDelegate == null)) {
                this.onBeginGetResourceDelegate = new BeginOperationDelegate(this.OnBeginGetResource);
            }
            if ((this.onEndGetResourceDelegate == null)) {
                this.onEndGetResourceDelegate = new EndOperationDelegate(this.OnEndGetResource);
            }
            if ((this.onGetResourceCompletedDelegate == null)) {
                this.onGetResourceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetResourceCompleted);
            }
            base.InvokeAsync(this.onBeginGetResourceDelegate, new object[] {
                        resName}, this.onEndGetResourceDelegate, this.onGetResourceCompletedDelegate, userState);
        }
        
        public bool CheckLogin(string username, string password, int mode) {
            return base.Channel.CheckLogin(username, password, mode);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCheckLogin(string username, string password, int mode, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCheckLogin(username, password, mode, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndCheckLogin(System.IAsyncResult result) {
            return base.Channel.EndCheckLogin(result);
        }
        
        private System.IAsyncResult OnBeginCheckLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            int mode = ((int)(inValues[2]));
            return this.BeginCheckLogin(username, password, mode, callback, asyncState);
        }
        
        private object[] OnEndCheckLogin(System.IAsyncResult result) {
            bool retVal = this.EndCheckLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCheckLoginCompleted(object state) {
            if ((this.CheckLoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CheckLoginCompleted(this, new CheckLoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CheckLoginAsync(string username, string password, int mode) {
            this.CheckLoginAsync(username, password, mode, null);
        }
        
        public void CheckLoginAsync(string username, string password, int mode, object userState) {
            if ((this.onBeginCheckLoginDelegate == null)) {
                this.onBeginCheckLoginDelegate = new BeginOperationDelegate(this.OnBeginCheckLogin);
            }
            if ((this.onEndCheckLoginDelegate == null)) {
                this.onEndCheckLoginDelegate = new EndOperationDelegate(this.OnEndCheckLogin);
            }
            if ((this.onCheckLoginCompletedDelegate == null)) {
                this.onCheckLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCheckLoginCompleted);
            }
            base.InvokeAsync(this.onBeginCheckLoginDelegate, new object[] {
                        username,
                        password,
                        mode}, this.onEndCheckLoginDelegate, this.onCheckLoginCompletedDelegate, userState);
        }
        
        public Client.GetMark_Service.SinhVien GetInfoSV(string MSSV) {
            return base.Channel.GetInfoSV(MSSV);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetInfoSV(string MSSV, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetInfoSV(MSSV, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Client.GetMark_Service.SinhVien EndGetInfoSV(System.IAsyncResult result) {
            return base.Channel.EndGetInfoSV(result);
        }
        
        private System.IAsyncResult OnBeginGetInfoSV(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string MSSV = ((string)(inValues[0]));
            return this.BeginGetInfoSV(MSSV, callback, asyncState);
        }
        
        private object[] OnEndGetInfoSV(System.IAsyncResult result) {
            Client.GetMark_Service.SinhVien retVal = this.EndGetInfoSV(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetInfoSVCompleted(object state) {
            if ((this.GetInfoSVCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetInfoSVCompleted(this, new GetInfoSVCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetInfoSVAsync(string MSSV) {
            this.GetInfoSVAsync(MSSV, null);
        }
        
        public void GetInfoSVAsync(string MSSV, object userState) {
            if ((this.onBeginGetInfoSVDelegate == null)) {
                this.onBeginGetInfoSVDelegate = new BeginOperationDelegate(this.OnBeginGetInfoSV);
            }
            if ((this.onEndGetInfoSVDelegate == null)) {
                this.onEndGetInfoSVDelegate = new EndOperationDelegate(this.OnEndGetInfoSV);
            }
            if ((this.onGetInfoSVCompletedDelegate == null)) {
                this.onGetInfoSVCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetInfoSVCompleted);
            }
            base.InvokeAsync(this.onBeginGetInfoSVDelegate, new object[] {
                        MSSV}, this.onEndGetInfoSVDelegate, this.onGetInfoSVCompletedDelegate, userState);
        }
        
        public bool UpdateInfoSV(Client.GetMark_Service.SinhVien SV) {
            return base.Channel.UpdateInfoSV(SV);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginUpdateInfoSV(Client.GetMark_Service.SinhVien SV, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateInfoSV(SV, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndUpdateInfoSV(System.IAsyncResult result) {
            return base.Channel.EndUpdateInfoSV(result);
        }
        
        private System.IAsyncResult OnBeginUpdateInfoSV(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Client.GetMark_Service.SinhVien SV = ((Client.GetMark_Service.SinhVien)(inValues[0]));
            return this.BeginUpdateInfoSV(SV, callback, asyncState);
        }
        
        private object[] OnEndUpdateInfoSV(System.IAsyncResult result) {
            bool retVal = this.EndUpdateInfoSV(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateInfoSVCompleted(object state) {
            if ((this.UpdateInfoSVCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateInfoSVCompleted(this, new UpdateInfoSVCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateInfoSVAsync(Client.GetMark_Service.SinhVien SV) {
            this.UpdateInfoSVAsync(SV, null);
        }
        
        public void UpdateInfoSVAsync(Client.GetMark_Service.SinhVien SV, object userState) {
            if ((this.onBeginUpdateInfoSVDelegate == null)) {
                this.onBeginUpdateInfoSVDelegate = new BeginOperationDelegate(this.OnBeginUpdateInfoSV);
            }
            if ((this.onEndUpdateInfoSVDelegate == null)) {
                this.onEndUpdateInfoSVDelegate = new EndOperationDelegate(this.OnEndUpdateInfoSV);
            }
            if ((this.onUpdateInfoSVCompletedDelegate == null)) {
                this.onUpdateInfoSVCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateInfoSVCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateInfoSVDelegate, new object[] {
                        SV}, this.onEndUpdateInfoSVDelegate, this.onUpdateInfoSVCompletedDelegate, userState);
        }
        
        public string[] List_HK() {
            return base.Channel.List_HK();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginList_HK(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginList_HK(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string[] EndList_HK(System.IAsyncResult result) {
            return base.Channel.EndList_HK(result);
        }
        
        private System.IAsyncResult OnBeginList_HK(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginList_HK(callback, asyncState);
        }
        
        private object[] OnEndList_HK(System.IAsyncResult result) {
            string[] retVal = this.EndList_HK(result);
            return new object[] {
                    retVal};
        }
        
        private void OnList_HKCompleted(object state) {
            if ((this.List_HKCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.List_HKCompleted(this, new List_HKCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void List_HKAsync() {
            this.List_HKAsync(null);
        }
        
        public void List_HKAsync(object userState) {
            if ((this.onBeginList_HKDelegate == null)) {
                this.onBeginList_HKDelegate = new BeginOperationDelegate(this.OnBeginList_HK);
            }
            if ((this.onEndList_HKDelegate == null)) {
                this.onEndList_HKDelegate = new EndOperationDelegate(this.OnEndList_HK);
            }
            if ((this.onList_HKCompletedDelegate == null)) {
                this.onList_HKCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnList_HKCompleted);
            }
            base.InvokeAsync(this.onBeginList_HKDelegate, null, this.onEndList_HKDelegate, this.onList_HKCompletedDelegate, userState);
        }
        
        public Client.GetMark_Service.KetQua[] KetQua_HK(string MSSV, string HK) {
            return base.Channel.KetQua_HK(MSSV, HK);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginKetQua_HK(string MSSV, string HK, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginKetQua_HK(MSSV, HK, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Client.GetMark_Service.KetQua[] EndKetQua_HK(System.IAsyncResult result) {
            return base.Channel.EndKetQua_HK(result);
        }
        
        private System.IAsyncResult OnBeginKetQua_HK(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string MSSV = ((string)(inValues[0]));
            string HK = ((string)(inValues[1]));
            return this.BeginKetQua_HK(MSSV, HK, callback, asyncState);
        }
        
        private object[] OnEndKetQua_HK(System.IAsyncResult result) {
            Client.GetMark_Service.KetQua[] retVal = this.EndKetQua_HK(result);
            return new object[] {
                    retVal};
        }
        
        private void OnKetQua_HKCompleted(object state) {
            if ((this.KetQua_HKCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.KetQua_HKCompleted(this, new KetQua_HKCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void KetQua_HKAsync(string MSSV, string HK) {
            this.KetQua_HKAsync(MSSV, HK, null);
        }
        
        public void KetQua_HKAsync(string MSSV, string HK, object userState) {
            if ((this.onBeginKetQua_HKDelegate == null)) {
                this.onBeginKetQua_HKDelegate = new BeginOperationDelegate(this.OnBeginKetQua_HK);
            }
            if ((this.onEndKetQua_HKDelegate == null)) {
                this.onEndKetQua_HKDelegate = new EndOperationDelegate(this.OnEndKetQua_HK);
            }
            if ((this.onKetQua_HKCompletedDelegate == null)) {
                this.onKetQua_HKCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnKetQua_HKCompleted);
            }
            base.InvokeAsync(this.onBeginKetQua_HKDelegate, new object[] {
                        MSSV,
                        HK}, this.onEndKetQua_HKDelegate, this.onKetQua_HKCompletedDelegate, userState);
        }
        
        public Client.GetMark_Service.SV_HK InfoSV_HK(string MSSV, string HK) {
            return base.Channel.InfoSV_HK(MSSV, HK);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginInfoSV_HK(string MSSV, string HK, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInfoSV_HK(MSSV, HK, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Client.GetMark_Service.SV_HK EndInfoSV_HK(System.IAsyncResult result) {
            return base.Channel.EndInfoSV_HK(result);
        }
        
        private System.IAsyncResult OnBeginInfoSV_HK(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string MSSV = ((string)(inValues[0]));
            string HK = ((string)(inValues[1]));
            return this.BeginInfoSV_HK(MSSV, HK, callback, asyncState);
        }
        
        private object[] OnEndInfoSV_HK(System.IAsyncResult result) {
            Client.GetMark_Service.SV_HK retVal = this.EndInfoSV_HK(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInfoSV_HKCompleted(object state) {
            if ((this.InfoSV_HKCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InfoSV_HKCompleted(this, new InfoSV_HKCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InfoSV_HKAsync(string MSSV, string HK) {
            this.InfoSV_HKAsync(MSSV, HK, null);
        }
        
        public void InfoSV_HKAsync(string MSSV, string HK, object userState) {
            if ((this.onBeginInfoSV_HKDelegate == null)) {
                this.onBeginInfoSV_HKDelegate = new BeginOperationDelegate(this.OnBeginInfoSV_HK);
            }
            if ((this.onEndInfoSV_HKDelegate == null)) {
                this.onEndInfoSV_HKDelegate = new EndOperationDelegate(this.OnEndInfoSV_HK);
            }
            if ((this.onInfoSV_HKCompletedDelegate == null)) {
                this.onInfoSV_HKCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInfoSV_HKCompleted);
            }
            base.InvokeAsync(this.onBeginInfoSV_HKDelegate, new object[] {
                        MSSV,
                        HK}, this.onEndInfoSV_HKDelegate, this.onInfoSV_HKCompletedDelegate, userState);
        }
        
        public Client.GetMark_Service.Statistic Info_Statistic(string MSSV) {
            return base.Channel.Info_Statistic(MSSV);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginInfo_Statistic(string MSSV, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInfo_Statistic(MSSV, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Client.GetMark_Service.Statistic EndInfo_Statistic(System.IAsyncResult result) {
            return base.Channel.EndInfo_Statistic(result);
        }
        
        private System.IAsyncResult OnBeginInfo_Statistic(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string MSSV = ((string)(inValues[0]));
            return this.BeginInfo_Statistic(MSSV, callback, asyncState);
        }
        
        private object[] OnEndInfo_Statistic(System.IAsyncResult result) {
            Client.GetMark_Service.Statistic retVal = this.EndInfo_Statistic(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInfo_StatisticCompleted(object state) {
            if ((this.Info_StatisticCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Info_StatisticCompleted(this, new Info_StatisticCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Info_StatisticAsync(string MSSV) {
            this.Info_StatisticAsync(MSSV, null);
        }
        
        public void Info_StatisticAsync(string MSSV, object userState) {
            if ((this.onBeginInfo_StatisticDelegate == null)) {
                this.onBeginInfo_StatisticDelegate = new BeginOperationDelegate(this.OnBeginInfo_Statistic);
            }
            if ((this.onEndInfo_StatisticDelegate == null)) {
                this.onEndInfo_StatisticDelegate = new EndOperationDelegate(this.OnEndInfo_Statistic);
            }
            if ((this.onInfo_StatisticCompletedDelegate == null)) {
                this.onInfo_StatisticCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInfo_StatisticCompleted);
            }
            base.InvokeAsync(this.onBeginInfo_StatisticDelegate, new object[] {
                        MSSV}, this.onEndInfo_StatisticDelegate, this.onInfo_StatisticCompletedDelegate, userState);
        }
    }
}
